apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: infrastructure
  source:
    path: apps/argocd
    repoURL: https://github.com/CallumHemsley/argo-cd-learnings.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true